### ISSUE TITLE
could not access Slack cookie database

### ISSUE THREAD

**Issue by henti** [rneatherway/gh-slack#15]
```
henti@henti:$ gh slack https://github.slack.com/archives/CMU22C4GL/p1663143988397279
could not access Slack cookie database: stat /home/henti/.config/Slack/Cookies: no such file or directory
```

Not really sure how to find or create this cookie ?

**Comment by rneatherway** [comment]
What is your operating system? Are you logged in to Slack on that machine? (that's how the cookie is created)

**Comment by henti** [comment]
```
PRETTY_NAME="Linux Mint 20.3"
```

Logged in to slack via browser. Does it require the app ?

**Comment by henti** [comment]
I've since figured out how to get the cookie from the browser, but not sure what DB format to create the file in.

**Comment by rneatherway** [comment]
Yes, the cookie extraction and subsequent token fetching requires you to be logged in using the app. I'd suggest just logging in as a one-off if you don't want to use it, that's going to be easier than trying to hack up the input this extension expects.

**Comment by henti** [comment]
Ok, will do :+1:
