### ISSUE TITLE
Didn't work for a mid-thread link

### ISSUE THREAD

**Issue by joshhale** [rneatherway/gh-slack#18]
Didn't work when I gave a link of a mid-thread comment, but did work when I gave a link for the first comment in the thread (see https://github.com/github/code-scanning/issues/7529)

```josh@MacBook-Pro ~ % gh slack -d https://github.slack.com/archives/C12CRNNQ5/p1665392210140119?thread_ts=1665153170.736519&cid=C12CRNNQ5
[1] 65001
zsh: no matches found: https://github.slack.com/archives/C12CRNNQ5/p1665392210140119?thread_ts=1665153170.736519
josh@MacBook-Pro ~ %
[1]  + exit 1     gh slack -d```

**Comment by rneatherway** [comment]
The `[1]` makes me think that a `&` somewhere has been interpreted by the shell and that's why this hasn't worked. I haven't been able to reproduce locally so I'm going to close this one out. Let me know if you have more details.
