### ISSUE TITLE
Add slack link (optionally?) to extracted output for issues

### ISSUE THREAD

**Issue by davebunte** [rneatherway/gh-slack#19]
When using this to post directly to an issue, I'd like to be able to have the link to the slack message included in the issue comment (perhaps as a URL link to the channel in the initial `Slack conversation archive of #CHANNEL`). At least while the Slack thread is still available, it would provide the ability to easily jump into Slack for additional context. (Plus, I'm assuming it should be relatively easy since the link is already provided as a required argument 😉.)

**Comment by rneatherway** [comment]
Nice suggestion, I've considered it before but not got around to it

**Comment by rneatherway** [comment]
@davebunte What do you think of #20? It means that `-d` will always include the header "Slack archive of conversation in <#channel|link that you passed on the command line>"

**Comment by davebunte** [comment]
Sorry, missed this. That looks great!
