### ISSUE TITLE
How to authenticate?

### ISSUE THREAD

**Issue by mwarkentin** [rneatherway/gh-slack#21]
This extension looks great, but I'm having problems getting it to work.

```
❯ gh slack https://sentry.slack.com/archives/ABCD1234/p7438238943272373
api token not found
```

Any guide or suggestions on what I need to do to get a working API token? Took a quick look through the code and it seems to try to pull it from a cookie, but I'm signed into the Native slack app, web app in Safari, and web app in Chrome, and I'm still getting the same issue.

In case it helps:

MacOS Ventura 13.0.1 (22A400)
Safari 16.1
Chrome 107.0.5304.121

**Comment by mwarkentin** [comment]
Oh cool, I'll take a look (relative novice at Go though) :) 

Someone in another slack pointed me in the direction of this project when I asked about cleaning up message dumps from Slack.

**Comment by rneatherway** [comment]
Cool, yeah, give it a go and if you get stuck feel free to ping me here or raise a draft PR with your progress so far that we can chat on.

**Comment by mwarkentin** [comment]
@rneatherway Unfortunately it doesn't look like the `gh config` is a generic key/value store, it only supports a few configurations:

```
❯ gh config set extensions.slack.team foo
! warning: 'extensions.slack.team' is not a known configuration key
```

```
❯ gh config
Display or change configuration settings for gh.

Current respected settings:
- git_protocol: the protocol to use for git clone and push operations (default: "https")
- editor: the text editor program to use for authoring text
- prompt: toggle interactive prompting in the terminal (default: "enabled")
- pager: the terminal pager program to send standard output to
- http_unix_socket: the path to a Unix socket through which to make an HTTP connection
- browser: the web browser to use for opening URLs
```

Maybe a feature request you can bring up internally? :D 

For now I'm working on adding it as a new cmd line argument, but definitely seems like you'd want some way to set the default so you don't need to define that each time. Maybe pull it from a `$GH_SLACK_TEAM` environment variable?

**Comment by rneatherway** [comment]
That's actually just a warning so it's not a problem to go ahead and use that key:

```
$ gh config set extensions.slack.team foo
! warning: 'extensions.slack.team' is not a known configuration key

$ gh config get extensions.slack.team
foo

$ cat ~/.config/gh/config.yml 
<snip>
extensions.slack.team: foo
```

**Comment by mwarkentin** [comment]
Excellent, will take another look at implementing the config option.

**Comment by mwarkentin** [comment]
This will be fixed by #23, thanks!

**Comment by rneatherway** [comment]
Version 0.0.12 has now been released :tada:

**Comment by mwarkentin** [comment]
Amazing, thanks!
