### ISSUE TITLE
Combine back-to-back messages from the same user

### ISSUE THREAD

**Issue by octokatherine** [rneatherway/gh-slack#26]
Hi! Feature request 😄 It would be great if back-to-back messages all from the same user were combined, so it only says their name once. It would be a little cleaner and easier to read the actual conversation. If not the default behavior, maybe an option.

for example rather than:

> **octokatherine** at 2023-02-13 06:09
>
> blah blah

> **octokatherine** at 2023-02-13 07:03
>
> bah blah blah blah

it would be:

> **octokatherine** at 2023-02-13 06:09
>
> blah blah
>
> bah blah blah blah

**Comment by octokatherine** [comment]
P.S. I got this idea from @cheshire137 who told me about this extension and said she manually combines messages from the same user

**Comment by cheshire137** [comment]
This could be great for us to pair on this Thursday, Katherine!

**Comment by rneatherway** [comment]
Seems like a good idea to me :grin:
