### ISSUE TITLE
api token not found

### ISSUE THREAD

**Issue by znull** [rneatherway/gh-slack#39]
I had gh-slack working previously. Maybe because of the upgrade to 0.0.16, I'm not sure, I'm now getting:
```
gh slack -d -i https://github.com/znull/znull/issues/1 https://github.slack.com/archives/...                                         
2023/05/05 11:41:45 net/http: invalid byte '\x15' in Cookie.Value; dropping invalid bytes
api token not found
```

**Comment by znull** [comment]
I'm not sure why, but deleting all slack entries from macos keychain and logging in again fixed this.

**Comment by sampart** [comment]
For others who find this, upgrading the extension solved this for me:

```shell
gh extension upgrade gh-slack
```
