### ISSUE TITLE
users response not OK - limit_required

### ISSUE THREAD

**Issue by rmoff** [rneatherway/gh-slack#48]
This tool is great - it works really well, except on one Slack group: 

```
gh slack read https://example.slack.com/archives/C1M5388TF/p1688463409836309
Error: users response not OK: {"ok":false,"error":"limit_required"}
```

There are ~30k users on this Slack, so perhaps [this is the issue](https://api.slack.com/methods/users.list#arg_limit)

> If the collection is too large you may experience `limit_required`

**Comment by rneatherway** [comment]
👋 Apologies for the slow reply, my notifications were going to a defunct email address. This should be fairly simple to address by adding paging to the `users` call https://github.com/rneatherway/gh-slack/blob/211b567ee13226729ae0162620989cff8a0ec528/internal/slackclient/client.go#L358

You could use this function as an example: https://github.com/rneatherway/gh-slack/blob/211b567ee13226729ae0162620989cff8a0ec528/internal/slackclient/client.go#L316

I'd be happy to review such a PR, or may get to it myself at some point!

**Comment by rneatherway** [comment]
This should be fixed by https://github.com/rneatherway/gh-slack/pull/61. Would you like to give it a test @rmoff?

**Comment by rneatherway** [comment]
Great! If you checkout the PR and then run

    go run ./cmd/gh-slack/ read https://example.slack.com/archives/C1M5388TF/p1688463409836309

that should be equivalent to the command that you pasted above.

**Comment by rmoff** [comment]
Works perfectly. thanks!

**Comment by rneatherway** [comment]
Released!
