### ISSUE TITLE
Did the detail flag go away?

### ISSUE THREAD

**Issue by maxbeizer** [rneatherway/gh-slack#49]
`-d` was a go-to flag for me as introduced in https://github.com/rneatherway/gh-slack/pull/20

Did that get removed at some point? If so any chance you'd consider bringing it back @rneatherway ?

Also 👋 I didn't get a chance to say goodbye but thanks for everything and I'm glad we got a chance to speak that one time 💖

**Comment by rneatherway** [comment]
I _think_ it should still be working. What behaviour are you seeing?

https://github.com/rneatherway/gh-slack/blob/211b567ee13226729ae0162620989cff8a0ec528/cmd/gh-slack/cmd/read.go#L70

(Likewise, I enjoyed chatting with you and enjoyed seeing your contributions from the middle distance!)

**Comment by maxbeizer** [comment]
Ah it does work! I was concerned as this was the help output I see

```
$gh slack --help
Usage:
  gh-slack [command]

  If no command is specified, the default is "read". The default command also requires a permalink argument <START> for the first message to fetch.
  Use "gh-slack read --help" for more information about the default command behaviour.

Examples:
  gh-slack -i <issue-url> <slack-permalink>  # defaults to read command
  gh-slack read <slack-permalink>
  gh-slack read -i <issue-url> <slack-permalink>
  gh-slack send -m <message> -c <channel-id> -t <team-name>

  # Example configuration (add to gh's configuration file at $HOME/.config/gh/config.yml):
  extensions:
    slack:
      team: foo
      channel: ops
      bot: robot        # Can be a user id (most reliable), bot profile name or username

Available Commands:
  completion  Generate the autocompletion script for the specified shell
  help        Help about any command
  read        Reads a Slack channel and outputs the messages as markdown
  send        Sends a message to a Slack channel

Flags:
  -h, --help      help for gh-slack
  -v, --verbose   Show verbose debug information

Use "gh-slack [command] --help" for more information about a command.
```

Apologies for not actually reading the source 🤦 . Should I open an issue to add the flag back to the help output?

**Comment by rneatherway** [comment]
The situation is a bit confusing since adding support to send messages as well. Reading messages, which is what `gh slack` has always done, is now under the `read` subcommand. However, for backward compatibility and general ergonomics that is also the default, so you may not even have noticed. You can access the specific help for the read command, rather than just a few examples, like this:

```
$ gh slack read -h
Usage:
  gh-slack read [flags] <START>

  where <START> is a required argument which should be permalink for the first message to fetch. Following messages are then fetched from that channel (or thread if applicable).

Examples:
  gh-slack read <slack-permalink>
  gh-slack read -i <issue-url> <slack-permalink>

Flags:
  -d, --details        Wrap the markdown output in HTML <details> tags
  -h, --help           help for read
  -i, --issue string   The URL of a repository to post the output as a new issue, or the URL of an issue (or pull request) to add a comment to
  -l, --limit int      Number of _channel_ messages to be fetched after the starting message (all thread messages are fetched) (default 20)
      --version        Output version information

Global Flags:
  -v, --verbose   Show verbose debug information
```

Is there any way that we can make this clearer?

**Comment by maxbeizer** [comment]
Hmm probably not tbh. This situation probably only applies to folks like me who got used to before send. Closing as I don't think there's anything to do here. Thanks again for this great piece of software 💖

**Comment by rneatherway** [comment]
Glad that it's still proving useful!
