### ISSUE TITLE
Unable to `send` to private channel

### ISSUE THREAD

**Issue by ACyphus** [rneatherway/gh-slack#50]
While trying out the functionality of the extension, I can `read` from private channels and `send` to public channels. However it seems that I can't `send` to private channels using either the channel id or name:

```
gh slack send -c redacted -t redacted -m 'Test Slack post from CLI'
Populating channel cache (this may take a while)...544...974...1421...1936...2402...2878...3318...3710...4149...4640...5136...5651...6243...6911...7610...8312...8315...8323...8432...done!
Error: could not find any channel with name "redacted"
```

Is this expected to work? Or is this a natural limitation of the extension/Slack API? @rneatherway 

Thanks for building this! It's helpful and cool 😎

**Comment by rneatherway** [comment]
Hi @ACyphus, glad to hear that you find the project useful!

The channel list is obtained using the `conversations.list` API and it looks like that method can be passed a list of `types`, which by default is only public channels: https://api.slack.com/methods/conversations.list#arg_types. In fact it looks like I left myself a TODO: https://github.com/rneatherway/gh-slack/blob/211b567ee13226729ae0162620989cff8a0ec528/internal/slackclient/client.go#L329-L331

Would you like to make a PR for this change? You should be able to just add `,private_channel` to the types parameter in the linked code. You can test local changes using `go run cmd/gh-slack/main.go`.
