### ISSUE TITLE
feature request: image support

### ISSUE THREAD

**Issue by znull** [rneatherway/gh-slack#52]
It would be super great if transferring a thread from slack to an issue would preserve images posted in the thread.

(Otherwise, thanks! gh-slack is extraordinarily useful)

**Comment by rneatherway** [comment]
That's a cool idea! I am pretty sure that looking for images in the messages would be fairly easy, somewhere around https://github.com/rneatherway/gh-slack/blob/6390aacd9ac11deeedf387eaf3cfdde961daf650/internal/markdown/markdown.go#L144

However, how would you add images to issues? I don't believe there is any way to upload images to an issue using the API: https://github.com/isaacs/github/issues/1133

**Comment by znull** [comment]
No idea! I didn't know the API didn't support that. 🤔
