### ISSUE TITLE
Additional flags for the `send` command

### ISSUE THREAD

**Issue by nobe4** [rneatherway/gh-slack#53]
👋 Thanks for this awesome extension, it has made my slack-archiving job much easier ✨

One pattern that I'm doing a lot is
1. send a message
2. pin the message
3. ... do some work on it ...
4. unpin the message

I am wondering if it would be possible to add a flag to `send` that pins the newly-sent message and/or shows the link to it so one can easily go to it.

E.g.

- Send a message and open it immediately:

  ```shell
  gh slack send -c 'where-we-work' -m ':thread: can we talk about something?' -o | xargs open
  ```

  PR for this, since it was quite easy: https://github.com/rneatherway/gh-slack/pull/54

- Send a message and pin it for later:
  ```shell
  gh slack send -c 'where-we-work' -m ':thread: can we talk about something?' -p
  Message pinned for later!
  ```

  This will require a bit more work and I am not currently versed enough in how the Slack client you wrote works, but if that has some interest I could dig it up a bit more.

Happy to hear feedback 🙏

**Comment by rneatherway** [comment]
Interesting ideas! No objection to adding some new functionality like this.

> * This will require a bit more work and I am not currently versed enough in how the Slack client you wrote works, but if that has some interest I could dig it up a bit more.

You'd need to add a call to `pins.add`, it looks like: https://api.slack.com/methods/pins.add

I experiment with this stuff by adding a new method in https://github.com/rneatherway/gh-slack/blob/main/internal/slackclient/client.go and changing e.g. `sendMessage` (https://github.com/rneatherway/gh-slack/blob/main/cmd/gh-slack/cmd/send.go#L81) so it just calls that method and dumps the JSON response. In this case you'll just be looking to verify that it actually does pin the message you're concerned with. Have a go and if you get stuck push a branch and I'll give you some hints.

**Comment by nobe4** [comment]
I thought about this more and I think another direction to take would be to have an `api` command that one can use to send and receive info to Slack.

With such an example, one could do:

```shell
ts="$(
  go run cmd/gh-slack/main.go \
    api post chat.postMessage \
    -t XXX \
    -b '{"channel":"YYY","text":"message to pin"}' \
    | jq -r '.ts'
)"

go run cmd/gh-slack/main.go \
  api post pins.add \
  -t XXX \
  -b '{"channel":"YYY","timestamp":"'"${ts}"'"}'
```

I've implemented such a command in https://github.com/rneatherway/gh-slack/pull/55 and done a couple of promising tests.

**Comment by rneatherway** [comment]
I think we can close this one with #55 merged and [released](https://github.com/rneatherway/gh-slack/releases/tag/0.0.21) right?
