### ISSUE TITLE
Slack client decoupling

### ISSUE THREAD

**Issue by nobe4** [rneatherway/gh-slack#56]
As mentioned in https://github.com/rneatherway/gh-slack/pull/55#issuecomment-1839189046, I suggested the idea of decoupling the slack client (i.e. https://github.com/rneatherway/gh-slack/tree/main/internal/slackclient) into its own module.

I have seen https://github.com/slack-go/slack, which looks awesome and very complete but also wrapping up a lot of functionalities in go functions instead of keeping the abstraction low.

I think having a Slack client object that only allows to easily send requests to the API would make it easy to extend and keep as simple as possible.

I think the real beauty of this project is the way it gets the token from the local slack installation. I would see this + a generic way to call the API/RTM enough for the base module.

**Comment by rneatherway** [comment]
Agreed, I think that's a nice idea to make this easier for other people to build upon. What you've done in the previous PR is nice for building small bash scripts with `jq` etc, but being able to write Go for larger things is better.

How about:
* Keep this repository here as the place to install `gh-slack`. There's no massive reason that this has to be `gh` plugin even, it's mainly that this was a very convenient package manager while I was working at GitHub.
* Create a new repository, something like `rneatherway/slack-core` (name suggestions welcome!). I'd add you as a contributor there and we can iterate on a design to point `gh-slack` to before doing a release that other people might depend on.

**Comment by rneatherway** [comment]
OK, I've had a go over at #57. Let's discuss over there?

**Comment by nobe4** [comment]
Yes! Thanks for doing this! 

I'll be mostly off until the 4th of Jan. 
Let's discuss more when I come back :) Have a great end of the year!

**Comment by rneatherway** [comment]
Sounds good, enjoy your holiday 😁
