### ISSUE TITLE
Add `gh-extension` topic to repository for discoverability

### ISSUE THREAD

**Issue by andyfeller** [rneatherway/gh-slack#58]
Firstly, @rneatherway, thank you for creating this beautiful CLI extension!

Secondly, I'd like it to be discoverable when using `gh ext browse`, which requires a `gh-extension` topic on the repository as describe in [GitHub Docs](https://docs.github.com/en/github-cli/github-cli/creating-github-cli-extensions#creating-an-interpreted-extension-manually):

> Optionally, to help other users discover your extension, add the repository topic gh-extension. This will make the extension appear on the [gh-extension topic page](https://github.com/topics/gh-extension). For more information about how to add a repository topic, see "[Classifying your repository with topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics)."

Should be easy peasy, then lemon squeezy.

**Comment by rneatherway** [comment]
Done!

**Comment by andyfeller** [comment]
✨ thanks, Robin; hope you've been enjoying your new journey ❤️

**Comment by rneatherway** [comment]
Cheers!
