### ISSUE TITLE
Include reference link intro to Slack message dump

### ISSUE THREAD

**Issue by JamesMGreene** [rneatherway/gh-slack#59]
When I use this extension, I find myself going back and editing the generated issue comment afterward to add an intro something like:

```md
From a [Slack discussion in `#channel`](link):
```

Could we add something like that into the extension instead? 🙏 

Totally fine with passing an additional flag to make it happen as well.

**Comment by rneatherway** [comment]
What version of the extension are you using? It looks like I added that a while back: https://github.com/rneatherway/gh-slack/commit/62ab452d86011ac2c5067818f4852f31f7e5b95d

**Comment by rneatherway** [comment]
Closing for now as I believe this is already done.

**Comment by JamesMGreene** [comment]
I was using `0.0.19`, which includes that commit. 🤔 

I'll re-open if I run into this again the next time I use it. 🤷

**Comment by JamesMGreene** [comment]
I am not seeing this behavior in practice.

```shell
$ gh --version
gh version 2.46.0 (2024-03-20)
https://github.com/cli/cli/releases/tag/v2.46.0

$ gh extension upgrade gh-slack
[slack]: already up to date
✓ Successfully upgraded extension
```

There isn't any reference link included in the comment (not at the top, nor bottom, for the record):

![Comment without any reference link](https://github.com/rneatherway/gh-slack/assets/417751/19c8ed47-b18a-4cd3-88b6-016c628df4c0)

The commit you reference mentions "Details mode", but I don't see anything in the documentation about that. Is there any additional setting or flag required to enable that behavior? 🤔 

The command I used was the most basic:

```shell
$ gh slack -i https://github.com/owner/repo/issues/123 https://biz.slack.com/archives/C0123456789/p1111111111111111
```

**Comment by rneatherway** [comment]
You can pass `-d` or `--details` to enable that mode, which is described in the output of `gh slack read --help`.

The code that actually does it is here:

https://github.com/rneatherway/gh-slack/blob/62ab452d86011ac2c5067818f4852f31f7e5b95d/internal/markdown/markdown.go#L146
