### ISSUE TITLE
Is it possible to supply slack auth info manually?

### ISSUE THREAD

**Issue by spicycode** [rneatherway/gh-slack#69]
My current gig doesn't allow for querying keychain to get auth in any scenario, so I'd need to manually supply if it was to be feasible.  From what I've looked through it doesn't seem like it's supported, but I figured it was worth asking.

**Comment by rneatherway** [comment]
Yes you can! If you look at the help, one of the examples is `eval $(gh-slack auth -t <team-name>)`. That `auth` subcommand prints two environment variables:

https://github.com/rneatherway/gh-slack/blob/main/cmd/gh-slack/cmd/auth.go#L37-L38

If you can get hold of these, for example from the chrome developer tools while logged in to Slack, then you should be fine.

**Comment by spicycode** [comment]
@rneatherway This exactly addresses what I was looking for, thank you so much!  I have to say this was by far my favorite `gh-cli` extension from my time at GitHub.  It makes a very common task so easy to accomplish.  Thank you again!
