### ISSUE TITLE
Unable to decrypt the Slack Cookie

### ISSUE THREAD

**Issue by nobe4** [rneatherway/gh-slack#71]
Starting today, I was unable to run any command, and `gh slack auth` yielded an error:

```
2024/11/01 10:06:03 net/http: invalid byte '\u0091' in Cookie.Value; dropping invalid bytes
Error: api token not found
```

System: macOS 15.0.1 (24A348)
Slack: 4.41.97
gh-slack: built from main on https://github.com/rneatherway/gh-slack and https://github.com/rneatherway/slack

---

After digging a bit, and adding logs, I noticed that the `cookie` sent to slack looked misformed:

```
cookie: �sD�\*Nh�?�3�����j��<D\�iǢxxoxd-[... the rest looks okay ...]
```

To reproduce my logs, have a look at:

- https://github.com/nobe4/gh-slack/pull/1
- https://github.com/rneatherway/slack/pull/5

**Comment by nobe4** [comment]
@koesie10 mentionned that this change might come about with https://chromium-review.googlesource.com/c/chromium/src/+/5792044

I tried in https://github.com/rneatherway/slack/pull/5/commits/50e0451ffb8c3ee0de91a78b3a6ec495be3e6549 to remove the 32 bytes "random" prefix and got it working again.

Turns out that those 32 bytes are the sha256 of `.slack.com`:

![Image](https://github.com/user-attachments/assets/17f5e5c7-3d72-4794-8cfc-9463f59b3b84)
![Image](https://github.com/user-attachments/assets/c0f401ce-e80c-4fa5-bb35-fc72d6ae0b17)

I'll get working on a PR to remove this prefix, and possibly the sha256 for `slack.com` as well.

**Comment by nobe4** [comment]
This should be fixed by https://github.com/rneatherway/slack/pull/6

**Comment by rneatherway** [comment]
I've done a fresh release of gh slack so should be all good to go. Thanks for the fix!
