### ISSUE TITLE
Error: conversations.replies response not OK, missing required fields channel and ts

### ISSUE THREAD

**Issue by cheshire137** [rneatherway/gh-slack#74]
I started getting an error recently with the extension when I try to copy a Slack thread:

```sh
% gh slack https://my-slack-thingy.slack.com/archives/urlfoo
Error: conversations.replies response not OK: {"ok":false,"error":"invalid_arguments","response_metadata":{"messages":["[ERROR] missing required field: channel","[ERROR] missing required field: ts"]}}
```

I confirmed I'm on the latest version of the extension:

```sh
% gh extension upgrade gh-slack
[slack]: already up to date
✓ Successfully checked extension upgrades
```

**Comment by rneatherway** [comment]
Ah, I just had a play around locally and it looks like `conversations.replies` should really be a `POST` but I've always used a `GET` here. Would you mind verifying that something like:

    gh slack api conversations.replies --body '{"ts": "12345.123456", "channel": "CXXXX"}'

works for you?

(you can construct that body from the thread URL, note the `.` six characters prior to the end of the timestamp)

**Comment by cheshire137** [comment]
👋🏻 Hi Robin! I filled in a real `channel` parameter but left the `ts` parameter from your example, I wasn't sure how to get `ts` from a real Slack thread. 🤔 Running that command gives me:

```sh
% gh slack api conversations.replies --body '{"ts": "12345.123456", "channel": "C041NH2DFUJ"}'
Error: failed to read gh-slack configuration value "extensions.slack.team" from "/Users/cheshire137/.config/gh/config.yml": could not find key "extensions"
```

Which feels like an earlier/different error, something with my config setup and less about the "conversations.replies response not OK" error. What does your .config/gh/config.yml file look like? Just the general shape I mean.

**Comment by rneatherway** [comment]
If you add:

```yaml
extensions:
    slack:
        team: github
```

That'll sort that problem (or you can pass `-t github` but that gets boring fast!).

Then to get the `ts` value from a thread URL take the last path component which is `p123456789123456`, drop the `p` and insert a `.` six characters from the end.

**Comment by rneatherway** [comment]
I just released a new version with https://github.com/rneatherway/gh-slack/pull/75 which you could also try upgrading to.

**Comment by cheshire137** [comment]
> or you can pass `-t github`

How'd you know I'm on the github team! 😆 

Thanks, got my config file updated. Trying `gh slack api conversations.replies --body '{"ts": "12345.123456", "channel": "C041NH2DFUJ"}'` now gives me:

```sh
{"ok":false,"error":"invalid_arguments","response_metadata":{"messages":["[ERROR] missing required field: channel","[ERROR] missing required field: ts"]}}
```

So at least consistent with the error the `read` command is giving me. 👍🏻 

> I just released a new version

I'll try upgrading now!

**Comment by cheshire137** [comment]
Okay, upgraded and it fixes the error response with `gh slack URL`, but seems to have a new bug: messages are repeated! I promise I did not say "hi folks" four times originally: 😅 

![screenshot of term output with 'hi folks' 4 times](https://github.com/user-attachments/assets/538ebd55-e6e5-4183-9930-bef72df030f9)

I tried with a couple Slack threads and not _all_ messages are repeated, but several are.

**Comment by rneatherway** [comment]
I've had a go at trying to reproduce that and I can't on my Slack instance. Do the threads with repeated messages have anything unusual in common?

**Comment by cheshire137** [comment]
Interesting. 🤔 Nothing that jumps out at me. I tried it with a short thread (only like 3 messages) and none were repeated. I tried it with a longer thread (30+ messages) and some were duplicated. I thought maybe duplicated messages had been edited by the author or something, but no, I don't see any edit indicators in Slack for them. Also, it seems like the duplication isn't at the message level, but rather elements within a message:

![screenshot with one line repeated and one showing just once](https://github.com/user-attachments/assets/714e7511-6737-45f7-9a5c-e92a10633caa)

Here the quoted chunk only showed up in the output once from `gh slack` where as the "eh, deferred loading's" piece came 4 times. Both pieces were in a single message in Slack:

![screenshot of Slack message](https://github.com/user-attachments/assets/12c33b37-5927-44c0-be39-11332fc224f2)

**Comment by rneatherway** [comment]
Interesting, OK. Here's a way you could debug it. So given the standard "read" command e.g.:

> gh slack https://sanity-io.slack.com/archives/C03RP3RDGFQ/p1733922502951009

Run the following command:

> gh slack api post conversations.replies -f ts=1733922502.951009 -f channel=C03RP3RDGFQ

Obviously you should substitute your own values for the timestamp (note the `.` as before!) and the channel. I've included the original URL for reference which hopefully makes that relationship more obvious.

You can then pipe the output to `jq` or similar and have a look at the json for the duplicated messages to see whether there is duplication in the message response too and if so what it looks like.

**Comment by cheshire137** [comment]
> substitute your own values for the timestamp

Note for future debugging: to get a real `ts` value, I used a command like:

```sh
gh slack api conversations.history -f channel=CHANNEL_ID_COPIED_FROM_SLACK -f limit=7 > ~/Desktop/tmp-api-output.json
```

Then looked at sample messages in the resulting JSON file to see their 'ts' field.

**Comment by rneatherway** [comment]
> to get a real `ts` value

Apologies if you already connected these dots and found it inconvenient, but to spell it out:

* Given a URL like the one I did above: https://sanity-io.slack.com/archives/C03RP3RDGFQ/p1733922502951009
* Take the final path component: `p1733922502951009`
* Remove the leading `p`: `1733922502951009`
* Insert a dot six characters before the end: `1733922502.951009`

**Comment by cheshire137** [comment]
Uhhh I think it's my terminal that is responsible for the duplicated lines, actually. I tried running your suggested `post conversations.replies` command in my terminal and the top of the output includes duplicated lines.

![Image](https://github.com/user-attachments/assets/3e6d2238-7a8a-44c6-a7b5-f65805977584)

If I run the `gh slack read` command via a Raycast script I have setup, one that pipes the output to `pbcopy` so it goes in my clipboard, I get no duplicated lines, even when I try copying a Slack thread that yesterday, in my terminal, had several duplicated message lines. 🫠

I'm using iTerm2, Build 3.5.11beta1. I think I'll be looking at other terminals. 😓 Sorry for the red herring! Now that the original 'response not OK' is fixed, I'll just keep using my Raycast script instead of running the command in iTerm2.

**Comment by cheshire137** [comment]
> Apologies if you already connected these dots

Oh no, I straight up did not connect those dots, so thank you for explaining how to go from thread URL => `ts` value without hitting the API first!

**Comment by rneatherway** [comment]
> I'm using iTerm2, Build 3.5.11beta1. I think I'll be looking at other terminals. 😓 Sorry for the red herring! Now that the original 'response not OK' is fixed, I'll just keep using my Raycast script instead of running the command in iTerm2.

Oh! No worries!

**Comment by cheshire137** [comment]
I rolled back to the [stable version](https://iterm2.com/downloads.html) of iTerm2, Build 3.5.10, and re-ran the `gh slack api post conversations.replies` command. No more duplicated lines. 😌 

![screenshot of terminal output with unique lines of text](https://github.com/user-attachments/assets/5cdf052d-eab2-406d-b95a-3dbb2d688848)
